sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '6'
before_script:
  - npm prune
script:
  - ./next-update-travis.sh
  - npm test
  # disable deploys for now - need new domain
  # because current domain used for testing bahmutov.com
  # is now a redirect to glebbahmutov.com :(
  # - cd test
  # - npm run deploy
  # - npm run list
  # - npm run prune
  # - echo There should be no deploys now
  # - npm run list
  # # back to main folder
  # - cd ..
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
